FROM maven:3-jdk-8
LABEL author=Suman
RUN git clone https://github.com/Suman/openmrs-core.git && cd openmrs-core && mvn clean install
WORKDIR /openmrs-core/webapp
EXPOSE 8080
CMD [ "mvn", "jetty:run"]
