---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-default-disk
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-default-pvc
  labels:
    app: mysqlpvc
  annotations:
    kubernetes.io/change-cause: "version 1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysqlpvc
  template:
    metadata:
      labels:
        app: mysqlpvc
        version: v1.0
    spec:
      containers:
        - image: mysql:8.0
          name: mysqlpvc
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
            - name: MYSQL_DATABASE
              value: azpvcdb
            - name: MYSQL_USER
              value: azuser
            - name: MYSQL_PASSWORD
              value: azuser123
          volumeMounts:
            - name: mysqldbdefault
              mountPath: /var/lib/mysql
          ports:
            - containerPort: 3306
      volumes:
        - name: mysqldbdefault
          persistentVolumeClaim:
            claimName: azure-default-disk


              
